// Mirror of the bot-side TEXT_DEFAULTS for the Challenges feature.
// Keys are read by LunaButlerMain's challenge handler; v1 dashboard shipped
// this list first — v2 preserves the same schema so admin-written overrides
// round-trip correctly through /api/admin/challenges/texts.

export const TEXT_CATEGORIES: Record<string, string[]> = {
  'Announcements': ['announce.title', 'announce.body', 'announce.body_with_desc', 'announce.footer'],
  'Voting': ['panel.header', 'panel.waiting', 'panel.vote_format', 'panel.more_entries', 'panel.stats', 'panel.footer', 'panel.selector', 'panel.selector_page', 'panel.selector_capped', 'panel.gallery_btn'],
  'Vote Responses': ['vote.confirmed', 'vote.self_error', 'vote.already_voted', 'vote.invalid_entry', 'vote.rate_limited', 'vote.unavailable'],
  'Anti-Alt': ['antialit.join_too_new', 'antialit.account_too_new', 'antialit.flag_reason', 'antialit.log_title', 'antialit.log_footer'],
  'Submissions': ['submit.images_only', 'submit.already_submitted'],
  'Gallery': ['gallery.title', 'gallery.no_entries'],
  'Results': ['results.title', 'results.no_votes', 'results.vote_total', 'results.participants', 'results.rewards_title', 'results.reward_line'],
  'Hall of Fame': ['hof.title', 'hof.empty', 'hof.entry', 'hof.set_success'],
  'Admin': ['admin.owner_only', 'admin.db_error', 'admin.unknown_cmd', 'admin.missing_params', 'admin.challenge_exists', 'admin.no_active', 'admin.not_participant', 'admin.specify_user', 'admin.specify_channel', 'admin.generic_error', 'admin.panel_post_fail'],
  'Create': ['create.success_title', 'create.success_desc'],
  'Remove': ['remove.success_title', 'remove.success_desc'],
  'Cancel': ['cancel.announce_title', 'cancel.announce_desc', 'cancel.success_title'],
  'Info Fields': ['info.participants', 'info.votes', 'info.submission_ch', 'info.voting_ch', 'info.created', 'info.expires', 'info.flagged', 'info.rewards', 'info.duration', 'info.log_channel'],
  'List': ['list.title', 'list.status_active', 'list.status_closed', 'list.status_cancelled', 'list.no_challenges'],
};

export const TEMPLATE_VARS = [
  '{username}', '{challenge_name}', '{vote_count}', '{entry_count}', '{rank}',
  '{reward}', '{user_id}', '{channel_id}', '{description}', '{medal}',
  '{count}', '{page}', '{total}',
  '{emoji.cross}', '{emoji.check}', '{emoji.trophy}', '{emoji.party}',
  '{emoji.lunari}', '{emoji.clock}', '{emoji.warning}', '{emoji.chart}',
];

export const TEXT_DEFAULTS: Record<string, string> = {
  'announce.title': '{emoji.party} تحدٍّ جديد: {challenge_name}',
  'announce.body': '🌙 **أرسل أفضل صورة لديك للمشاركة.**\nيُسمح بصورة واحدة فقط لكل مشارك.',
  'announce.body_with_desc': '{description}\n\n🌙 **أرسل أفضل صورة لديك للمشاركة.**\nيُسمح بصورة واحدة فقط لكل مشارك.',
  'announce.footer': 'بالتوفيق للجميع 🌙',
  'panel.header': '🌙 يسعدني تقديم هذا التحدي — اختاروا المشاركة الأفضل',
  'panel.waiting': '*🌙 الساحة جاهزة — بانتظار أول مشاركة...*',
  'panel.vote_format': '{medal} **{username}** — {vote_count} صوت',
  'panel.more_entries': '*و {count} مشارك آخر...*',
  'panel.stats': '👥 **{entry_count}** مشارك | 🗳️ **{vote_count}** صوت',
  'panel.footer': 'صوت واحد لكل عضو · التصويت لنفسك غير مسموح',
  'panel.selector': '🌙 اختر من تودّ التصويت له...',
  'panel.selector_page': '🌙 اختر من تودّ التصويت له ({page}/{total})...',
  'panel.selector_capped': '🌙 اختر من تودّ التصويت له (أول 25)...',
  'panel.gallery_btn': '📸 تصفح الصور',
  'vote.confirmed': '🌙 تم تسجيل صوتك لصالح **{username}**. شكراً لمشاركتك!',
  'vote.self_error': '{emoji.cross} لا يمكنك التصويت لنفسك.',
  'vote.already_voted': '{emoji.cross} لقد أدليت بصوتك مسبقاً في هذا التحدي.',
  'vote.invalid_entry': '{emoji.cross} مشارك غير موجود.',
  'vote.rate_limited': '{emoji.clock} انتظر قليلاً قبل التصويت مرة أخرى.',
  'vote.unavailable': '{emoji.cross} التحدي غير متاح.',
  'antialit.join_too_new': '{emoji.clock} يجب أن تكون عضواً في السيرفر لمدة ساعة على الأقل للتصويت.',
  'antialit.account_too_new': '🛡️ يجب أن يكون عمر حسابك 7 أيام على الأقل للتصويت.',
  'antialit.flag_reason': '{count} حسابات جديدة صوّتت لنفس المشارك خلال 24 ساعة',
  'antialit.log_title': '🚩 تصويت مشبوه',
  'antialit.log_footer': 'التصويت مسجّل — يمكن إزالته بواسطة /challenge remove',
  'submit.images_only': '📸 عذراً <@{user_id}>، هذه القناة مخصصة للصور فقط.',
  'submit.already_submitted': '{emoji.check} <@{user_id}>، مشاركتك مسجّلة بالفعل. بالتوفيق!',
  'gallery.title': '📸 معرض: {challenge_name}',
  'gallery.no_entries': '{emoji.cross} لا توجد مشاركات.',
  'results.title': '{emoji.trophy} انتهى التحدي — النتائج النهائية: {challenge_name}',
  'results.no_votes': 'لا توجد أصوات.',
  'results.vote_total': '🗳️ إجمالي الأصوات',
  'results.participants': '👥 المشاركين',
  'results.rewards_title': '{emoji.lunari} الجوائز',
  'results.reward_line': '{medal} <@{user_id}> — **{reward}** لوناري',
  'hof.title': '🏛️ قاعة الأبطال',
  'hof.empty': '*لا يوجد أبطال بعد...*',
  'hof.entry': '{medal} **{challenge_name}** — {username} ({vote_count} صوت)',
  'hof.set_success': '{emoji.check} تم تعيين قاعة الأبطال',
  'admin.owner_only': '🔒 عذراً، هذا الأمر مخصص للإدارة فقط.',
  'admin.db_error': '{emoji.cross} قاعدة البيانات غير متصلة.',
  'admin.unknown_cmd': '{emoji.cross} أمر غير معروف.',
  'admin.missing_params': '{emoji.cross} يرجى تحديد جميع الخيارات المطلوبة.',
  'admin.challenge_exists': '{emoji.warning} يوجد تحدي نشط!\n**{challenge_name}**\nاستخدم `/challenge close` أو `/challenge cancel`',
  'admin.no_active': '{emoji.cross} لا يوجد تحدي نشط.',
  'admin.not_participant': '{emoji.cross} المستخدم ليس مشاركاً.',
  'admin.specify_user': '{emoji.cross} حدد المستخدم.',
  'admin.specify_channel': '{emoji.cross} حدد القناة.',
  'admin.generic_error': '{emoji.cross} حدث خطأ.',
  'admin.panel_post_fail': '{emoji.cross} فشل في إرسال لوحة التصويت في <#{channel_id}>',
  'create.success_title': '{emoji.check} تم إعداد التحدي بنجاح',
  'create.success_desc': '**{challenge_name}**\nالتصويت مباشر — يتحدّث تلقائياً مع كل مشاركة جديدة',
  'remove.success_title': '{emoji.check} تم إزالة المشارك',
  'remove.success_desc': 'تم إزالة **{username}** وجميع أصواته من التحدي.',
  'cancel.announce_title': '{emoji.warning} تم إلغاء التحدي',
  'cancel.announce_desc': 'تم إلغاء تحدي **{challenge_name}** بقرار من الإدارة.',
  'cancel.success_title': '{emoji.check} تم إلغاء التحدي',
  'info.participants': '👥 المشاركين',
  'info.votes': '🗳️ الأصوات',
  'info.submission_ch': '📸 الإرسال',
  'info.voting_ch': '🗳️ التصويت',
  'info.created': '📅 تاريخ الإنشاء',
  'info.expires': '{emoji.clock} ينتهي',
  'info.flagged': '🚩 مشبوه',
  'info.rewards': '{emoji.lunari} الجوائز',
  'info.duration': '{emoji.clock} المدة',
  'info.log_channel': '📋 السجل',
  'list.title': '{emoji.chart} سجل التحديات',
  'list.status_active': '🔴 مباشر',
  'list.status_closed': '🏆',
  'list.status_cancelled': '❌',
  'list.no_challenges': '{emoji.cross} لا توجد تحديات.',
};
